### ISSUE TITLE
Old instructions

### ISSUE THREAD

**Issue by guyluz11** [BinghamtonRover/Video#4]
Current reamde instrcations state to run  `dart run :camera <camera-name>` but there is no file name camera in bin so I am getting this error  
```dart
dart run :camera /dev/video0
Could not find `bin/camera.dart` in package `video`.
```

also found the file in another dir but it does not contain main so can't run it the same

**Comment by guyluz11** [comment]
I think I have found it 
I need to change `constants.dart` cameraNames to `/dev/video0`.

Let me know

**Comment by Levi-Lesches** [comment]
Fixed, that test executable has been moved to `opencv_ffi` as it is more suited to general camera IO and OpenCV than this program specifically.
